#!/usr/bin/env php
<?php declare(strict_types=1);

require __DIR__ . '/vendor/autoload.php';

// No input validation. If you mess it up, the app will crash.
[$day, $part] = $argv;

// Read example.txt or input.txt
$source = isset($argv[2]) && $argv[2] === '--example' ? 'example' : 'input';
$input = file(__DIR__ . "/src/Day{$day}/input/{$source}.txt");

/** @var Winkbrace\Advent2025\Contracts\Solver $class */
$class = "\\Winkbrace\\Advent2025\\Day{$day}\\Solver{$day}";
$method = "solve{$part}";
$solution = new $class($input)->$method();

echo "\n\nSolution to $day $part: $solution\n";
