#!/usr/bin/env php
<?php declare(strict_types=1);

require __DIR__ . '/vendor/autoload.php';

// No input validation. If you mess it up, the app will crash.
[$_, $day, $part] = $argv;

if (in_array('--debug', $argv)) {
    define('DEBUG', true);
}

// Read example.txt or input.txt
$source = in_array('--example', $argv) ? 'example' : 'input';
$input = array_map(
            fn (string $line) => rtrim($line, "\n\r"),
            file(__DIR__ . "/src/Day{$day}/input/{$source}.txt"),
        );

/** @var Winkbrace\Advent2025\Contracts\Solver $class */
$class = "\\Winkbrace\\Advent2025\\Day{$day}\\Solver{$day}";
$method = "solve{$part}";
$solution = new $class($input)->$method();

echo "\nSolution to $day $part: $solution\n";
